SumOfUs/homepage

- Gemfile
- Gemfile.lock
- config.rb
- locales/en.yml
- package.json
- source/javascripts/homepage.js
- source/javascripts/show_errors.js
- source/javascripts/sumofus/backbone/signup_form.js
- source/javascripts/sumofus/backbone/sweet_placeholder.js
- source/localizable/_country_options.slim
- source/localizable/index.html.slim
- source/stylesheets/homepage.css.scss
- source/stylesheets/sumofus/components/form.scss
- source/stylesheets/sumofus/global/interactive.scss
This PR makes the signup box work on the homepage. It also adds sweet placeholders that get small on field focus, which I'll port to Champaign when we unify the javascript. They look like this (but with smooth transitions the gif fails to capture)
> Working signup

- config.rb
- source/localizable/_faqs.slim
- source/pages/prismic.html.slim
@osahyoun I'm going to merge all the prismic stuff together so that there's one branch with everything that you can work from, and so I can make a last PR.
> Creating an faq page (beginnings)

- source/pages/de/contact.html.md.erb
- source/pages/en/contact.html.md.erb
- source/pages/es/contact.html.md.erb
- Changed the contact number for all 3 languages
> Phone number changes:

- source/localizable/_footer.slim
- source/stylesheets/_pages.scss
- Added instagram icon and redirected it to sumofus instagram page
> Instagram changes:

- source/localizable/_footer.slim
- Added facebook pixel tracker in footer
> FB Pixel Changes:

- source/stylesheets/_homepage.scss
- source/stylesheets/_pages.scss
- source/stylesheets/site.css.scss
- source/stylesheets/sumofus/components/button.scss
- source/stylesheets/sumofus/components/campaign-tile.scss
- source/stylesheets/sumofus/components/footer.scss
- source/stylesheets/sumofus/components/form.scss
- source/stylesheets/sumofus/components/funding-table.scss
- source/stylesheets/sumofus/components/fundraiser.scss
- source/stylesheets/sumofus/components/header.scss
- source/stylesheets/sumofus/components/modal.scss
- source/stylesheets/sumofus/components/petition.scss
- source/stylesheets/sumofus/components/press-tile.scss
- source/stylesheets/sumofus/components/staff.scss
- source/stylesheets/sumofus/components/thermometer.scss
- source/stylesheets/sumofus/global/colors.scss
- source/stylesheets/sumofus/global/typography.scss
- source/stylesheets/sumofus/pages/funding.scss
- source/stylesheets/sumofus/pages/privacy.scss
> common variables for colors

- source/stylesheets/_pages.scss
> Decrease footer size

- source/pages/de/opted_in.html.md.erb
- source/pages/de/opted_out.html.md.erb
- source/pages/de/optout.html.md.erb
- source/pages/en/opted_in.html.md.erb
- source/pages/en/opted_out.html.md.erb
- source/pages/en/optout.html.md.erb
- source/pages/es/opted_in.html.md.erb
- source/pages/es/opted_out.html.md.erb
- source/pages/es/optout.html.md.erb
- source/pages/fr/opted_in.html.md.erb
- source/pages/fr/opted_out.html.md.erb
- source/pages/fr/optout.html.md.erb
- source/stylesheets/sumofus/global/layout.scss
Ticket:
https://app.asana.com/0/1119304937718815/1149746244484305
> Message changes

- config.rb
Ticket:
https://app.asana.com/0/1119304937718815/1149968321576793/f
> Update api url to production from staging

- source/javascripts/sumofus/backbone/campaigns.js
- source/stylesheets/sumofus/components/campaign-tile.scss
Fix: Champaign image gets squeezed.
> Fix: champaign image squeezed

- source/layouts/home.slim
Request from Anne on email subjected as _PR Product - Getting rid of pop-up on our website_
> Dont show modal on homepage

- source/javascripts/sumofus/backbone/action_stream.js
- source/javascripts/sumofus/backbone/signup_form.js
- source/layouts/home.slim
- source/localizable/index.html.slim
- source/pages/es/contact.html.md.erb
- source/stylesheets/application.css.scss
- source/stylesheets/sumofus/components/form.scss
- Fixed the inputs of join us form 
- Websocket connection has been commented
> Join Us Form

- locales/ar.yml
- source/localizable/_nav.slim
These sections of the page will be hidden for the Arabic version.
Changed the email on the media page (also updated it on Transifex)
NOTE: Transifex integration with GitHub is not working; we need to fix that.
> Hide Story of Us and Covid Links for Arabic Version

- source/pages/ar/contact.html.md.erb
Product request to modify the Arabic version of the contact page just to have two emails, one for English and another for Arabic inquiries.
https://app.asana.com/0/1119304937718815/1201939164158948/f
> Changed Arabic Contact Emails

- locales/ar.yml
The donate links redirected to the English version because the page wasn't ready yet.
Azza created the page on Champaign, we are ready to publish it and we need to update the URL on the homepage links.
https://app.asana.com/0/1119304937718815/1201838197104600/f
> Updated donate page URL for Arabic

- config.rb
- locales/ar.yml
- locales/de.yml
- locales/en.yml
- locales/es.yml
- locales/fr.yml
- locales/nl.yml
- locales/pt.yml
- source/localizable/_nav.slim
- source/pages/ar/eko.html.md.erb
- source/pages/de/eko.html.md.erb
- source/pages/en/eko.html.md.erb
- source/pages/es/eko.html.md.erb
- source/pages/fr/eko.html.md.erb
- source/pages/nl/eko.html.md.erb
- source/pages/pt/eko.html.md.erb
- source/stylesheets/_pages.scss
- source/stylesheets/application.css.scss
- source/stylesheets/sumofus/pages/eko.scss
* Show a banner announcing the Ekō site launch
* Include a "Read More" link  to a page with more information about the rebranding
* Show the link for all visitors coming to the page starting on Jan 1st
* If the visitor clicks on the close or read more buttons, hide the banner and don't show it for the same visitor on the same device (using a cookie for this functionality).
* The read more link redirects to `/eko` which is a new landing page with more information about the rebranding
> Eko Announcement Banner and Landing Page

- locales/ar.yml
- locales/de.yml
- locales/en.yml
- locales/es.yml
- locales/fr.yml
- locales/nl.yml
- locales/pt.yml
Andrea requested these copy changes.
> Copy update for eko banner

- locales/de.yml
- locales/en.yml
- locales/es.yml
- locales/fr.yml
- locales/pt.yml
- source/localizable/_nav.slim
* changed tagline
* Hide storyofus page
> Changed sou tagline with Ekō tagline

- source/pages/de/privacy.html.md.erb
- source/pages/en/privacy.html.md.erb
- source/pages/es/privacy.html.md.erb
- source/pages/fr/privacy.html.md.erb
- source/pages/nl/privacy.html.md.erb
- source/pages/pt/privacy.html.md.erb
Updated postal address of netherlands across all languages except Arabic
> Update postal address Netherlands

- source/localizable/_head_tags.slim
Asana Ticket - [Add Meta meta tag to HTML source code of eko.org homepage](https://app.asana.com/0/1201335017674028/1203880204623829/f)
Description: 
We need to verify our new eko.org domain with Meta in order to continue running Facebook ads. There are a few ways to do this, but adding a meta tag to the HTML source code of the eko.org homepage seems like the simplest way to do it
Screenshots:
> Update meta tag for Meta verification

- locales/ar.yml
- locales/de.yml
- locales/en.yml
- locales/es.yml
- locales/fr.yml
- locales/nl.yml
- locales/pt.yml
- source/localizable/_footer.slim
- source/localizable/index.html.slim
* Replacing old social media links with the new Ekō accounts
https://app.asana.com/0/1119304937718815/1203959769632434/f
> Updating social media links to use Ekō accounts

- locales/ar.yml
- locales/de.yml
- locales/en.yml
- locales/es.yml
- locales/fr.yml
- locales/nl.yml
- locales/pt.yml
- source/localizable/_nav.slim
> Nav bar updates

- source/localizable/_footer.slim
- source/localizable/_head_tags.slim
* Adding google tag script to start sending data to GA4
https://app.asana.com/0/0/1203969282058436/f
> Adding gtag script

- source/404.html
- source/localizable/_head_tags.slim
- source/localizable/_modal.slim
- source/localizable/_nav.slim
- source/stylesheets/_homepage.scss
- source/stylesheets/_pages.scss
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204666408484319
> Update logo references

- locales/ar.yml
- locales/de.yml
- locales/en.yml
- locales/es.yml
- locales/fr.yml
- locales/nl.yml
- locales/pt.yml
- source/layouts/media.slim
- Adds new phone number as per email received from FinOps team
https://ekomovement.atlassian.net/browse/SCRUM-2394
> Adds new phone number

- source/pages/ar/contact.html.md.erb
- source/pages/de/contact.html.md.erb
- source/pages/en/contact.html.md.erb
- source/pages/es/contact.html.md.erb
- source/pages/fr/contact.html.md.erb
- source/pages/nl/contact.html.md.erb
- source/pages/pt/contact.html.md.erb
- The Dutch contact page was broken, it has been fixed
- Removes New York message from virtual office language
https://ekomovement.atlassian.net/browse/SCRUM-2506
> Updates language on contact page
